"""detector slim OBB + physical shape training helpers."""

from .data import DetectorDataBuilder
from .decode import (
    DETECTOR_MODE_FLUX_CALIB_GATE,
    DETECTOR_MODE_FLUX_REFINE,
    DETECTOR_MODE_SIZE,
    DETECTOR_MODE_SHARED_ANGLE,
    DETECTOR_NB_ANGLE,
    DETECTOR_NB_PARAM,
    DETECTOR_TARGET_STRIDE,
    DETECTOR_TOTAL_AUX,
    decode_rows_obb,
    decode_target_box,
    normalize_flux_decode_mode,
    normalize_slim_mode,
    detector_catalog_arrays,
    detector_layout,
    detector_target_dim,
)
from .hard_group_sampler import HardGroupSamplerConfig
from .runtime import (
    DEFAULT_RUN_DIR,
    DEFAULT_TARGET_SOURCE,
    DEFAULT_GEOMETRY_RUN_DIR,
    DEFAULT_TARGET_SOURCE_RUN_DIR,
    GEOMETRY_DIR,
    TARGET_SOURCE_DIR,
    ANGLE_DIR,
    CANDIDATE_DIR,
    DETECTOR_DIR,
    configure_paths,
    default_run_dir_for_target_source,
    install_numba_fallback_if_needed,
    normalize_target_source,
    target_table_path,
)

__all__ = [
    "DEFAULT_RUN_DIR",
    "DEFAULT_TARGET_SOURCE",
    "DEFAULT_GEOMETRY_RUN_DIR",
    "DEFAULT_TARGET_SOURCE_RUN_DIR",
    "GEOMETRY_DIR",
    "TARGET_SOURCE_DIR",
    "ANGLE_DIR",
    "CANDIDATE_DIR",
    "DETECTOR_DIR",
    "DETECTOR_MODE_FLUX_CALIB_GATE",
    "DETECTOR_MODE_FLUX_REFINE",
    "DETECTOR_MODE_SIZE",
    "DETECTOR_MODE_SHARED_ANGLE",
    "DETECTOR_NB_ANGLE",
    "DETECTOR_NB_PARAM",
    "DETECTOR_TARGET_STRIDE",
    "DETECTOR_TOTAL_AUX",
    "HardGroupSamplerConfig",
    "DetectorDataBuilder",
    "configure_paths",
    "default_run_dir_for_target_source",
    "decode_rows_obb",
    "decode_target_box",
    "install_numba_fallback_if_needed",
    "normalize_flux_decode_mode",
    "normalize_slim_mode",
    "normalize_target_source",
    "target_table_path",
    "detector_catalog_arrays",
    "detector_layout",
    "detector_target_dim",
]
