"""V4d slim OBB + physical shape training helpers."""

from .data import V4DPhysDataBuilder
from .decode import (
    V4D_MODE_FLUX_CALIB_GATE_SIZE_ANGLE,
    V4D_MODE_FLUX_REFINE_SIZE_ANGLE,
    V4D_MODE_SIZE,
    V4D_MODE_SIZE_ANGLE,
    V4D_NB_ANGLE,
    V4D_NB_PARAM,
    V4D_TARGET_STRIDE,
    V4D_TOTAL_AUX,
    decode_rows_obb,
    decode_target_box,
    normalize_flux_decode_mode,
    normalize_slim_mode,
    v4d_catalog_arrays,
    v4d_layout,
    v4d_target_dim,
)
from .hard_group_sampler import HardGroupSamplerConfig
from .runtime import (
    DEFAULT_RUN_DIR,
    DEFAULT_TARGET_SOURCE,
    DEFAULT_V1_RUN_DIR,
    DEFAULT_V1A_RUN_DIR,
    V1_DIR,
    V1A_DIR,
    V2_DIR,
    V25_DIR,
    V4D_DIR,
    configure_paths,
    default_run_dir_for_target_source,
    install_numba_fallback_if_needed,
    normalize_target_source,
    target_table_path,
)

__all__ = [
    "DEFAULT_RUN_DIR",
    "DEFAULT_TARGET_SOURCE",
    "DEFAULT_V1_RUN_DIR",
    "DEFAULT_V1A_RUN_DIR",
    "V1_DIR",
    "V1A_DIR",
    "V2_DIR",
    "V25_DIR",
    "V4D_DIR",
    "V4D_MODE_FLUX_CALIB_GATE_SIZE_ANGLE",
    "V4D_MODE_FLUX_REFINE_SIZE_ANGLE",
    "V4D_MODE_SIZE",
    "V4D_MODE_SIZE_ANGLE",
    "V4D_NB_ANGLE",
    "V4D_NB_PARAM",
    "V4D_TARGET_STRIDE",
    "V4D_TOTAL_AUX",
    "HardGroupSamplerConfig",
    "V4DPhysDataBuilder",
    "configure_paths",
    "default_run_dir_for_target_source",
    "decode_rows_obb",
    "decode_target_box",
    "install_numba_fallback_if_needed",
    "normalize_flux_decode_mode",
    "normalize_slim_mode",
    "normalize_target_source",
    "target_table_path",
    "v4d_catalog_arrays",
    "v4d_layout",
    "v4d_target_dim",
]
